mimblewimble/site

index.md

I don't have write access here - just spotted this.

typo (cycle)

---

index.md

testnet2 has been released, and work is being done on testnet3

updated to reflect latest testnet versions

---

friends.md

* Adding Guy Corem to Friends of Grin after [his 0.1 donation](https://blockchair.com/bitcoin/transaction/ee9a2bbb80251d6b97a0ed8d91463f048b11a6d3af10e2cb7a164767718efc6d)
* Sorting list of individual donors alphabetically (based on last name)

Add Guy Corem to Friends of Grin and sort individuals alphabetically

---

grincon_sponsorship.md

fixing the broken formatting of the table

fix Grincon sponsorship package table

---

friends.md

Fixes an issue where the beam logo wasn't scaling properly on different devices

fix beam dynamic logo scaling

---

friends.md

https://www.blockchain.com/en/btc/tx/fcf92ad761d8f46ed6dc45fcde7167fd1259c89356bb4f086096564a37093cd8

add Yan Pritzker

---

sec_audit.md

Yeastplume hardware wallet address, will convert received funds to bitcoin and send to btc mu-sig.

Add zcash t-address

---

_includes/navigation.html

Fix Build Steps link

---

_includes/navigation.html
_layouts/page.html
assets/css/main.scss
sec_audit.md

* Fix`sec_audit` on small screens (it's really responsive currently)
* General clean up of CSS
* Percentage and bar now depend on one variable `current_amount`

CSS cleanup and fix responsiveness issue in sec_audit

---

.gitignore
campaigns.md
funding.md
yeastplume.md

@ignopeverell @yeastplume @lehnberg

Keep track of past campaigns 

---

README.md
page-contribution-howto.md

Add instructions for deploying the site

---

_includes/navigation.html

More obvious from where to download Grin

---

friends.md

https://www.blocktrail.com/BTC/tx/76ea404a121ff508ba3d5881046342c72cd5951057e283acc8646e850bf90d6a

adds Hendrik Richter

---

.gitignore
_includes/footer.html
_includes/navigation.html

We don't really use "Mimwim" anywhere else.

rename Mimwim -> GrinMW

---

friends.md

https://etherscan.io/tx/0xc36b33d69feaa6c450d832d2e0b04b32fe1c15935409f5c4bb98ee4193936b60

Add Bart Mol to friends of Grin

---

_includes/navigation.html
index.md

- Update the navbar and website bar to show the updated status of the network
- change buttons from yellow to green

Update Floonet to Live

---

index.md

* mainnet capitalization
* floonet capitalization
* onwards and upwards

mainnet capitalization

---

friends.md

fix friends of grin columns

---

_includes/footer.html

add community and event wiki links to footer

---

campaigns.md
funding.md

Latest is over

---

friends.md

Individual reached out via email and sent approx $100 to the general dev fund - 
https://www.blockchain.com/ru/btc/address/3ChVP627KU5w4zu2rieFPF3wGXWQgmhvrs
Asked to be included on FoG as "Alex (X) Sherman".

add Alex (X) Sherman to FoG

---

assets/csv/entities.csv

As per https://github.com/mimblewimble/site/pull/108#pullrequestreview-212742412

update Aurel description

---

_sass/_markdown.scss
_sass/friends.scss
friends.html

* Show correct usd amount in donation
* Skip listing on leaderboard if it's missing in entities.csv without breaking
* Tweak: do not show decimals for usd amounts

 fix leaderboard bugs

---

assets/csv/entities.csv

- add `description` part
- remove the duplicated one

add SparkPool 'description' part

---

friends.html

@lehnberg Resolves #115.
Also, site will not break if this PR is merged before mimblewimble/grin-pm#89.
I.e. `misc_support.csv` will be ignored if it's unavailable.

add leaderboard support for misc_support.csv

---

friends.html

Related incoming log: https://github.com/mimblewimble/grin-pm/pull/95
To: Grin General Fund
Amount: 500 GRIN
Reference: https://www.grin-forum.org/t/give-grin-a-chinese-name-grin/4376/105
Slate ID: 5cfdecaa-dc97-413e-9588-ccb1ced93036

Liu Jie personal donation

---

assets/csv/entities.csv
friends.html

Add hwph and Qi Tian to friends of grin and Poloniex to list of entities as per https://github.com/mimblewimble/grin-pm/pull/153

Add new donors to friends of grin

---

friends.html

As per https://github.com/mimblewimble/grin-pm/pull/159

add xiake coin, fengqingyang, PANDA, Tensor Turbulence to FoG

---

general_funding.md

eth funding address

---

friends.html

As per https://github.com/mimblewimble/grin-pm/pull/195

add John Lee (jl2fa) to friends of grin

---

_includes/footer.html
_layouts/default.html
index.html

* Corrects URL
* Adds link to white paper history
* Adds link to security repo
* Fixes a typo in the hamburger menu
* Makes some of the main page copy more precise

Fixes to new site

---

_includes/navigation.html
_layouts/default-black.html
_layouts/default.html
open-research-problems.md

Add research page with open research problems

---

assets/csv/entities.csv

This PR:
* Adds a description to QTUMs entry
* Adds the anonymous donor responsible for the Nov 11 donation

Update friends of grin leaderboard entities

---

download.html

Add snap command to downloads page

feat: add snap command to install grin and grin-wallet

---

friends.html

As per https://github.com/mimblewimble/grin-pm/pull/229

Add zhuroulao to FoG

---

_layouts/default.html
assets/css/main.scss

It's been more than a month so I think we can safely remove it.

Remove HF banner

---

governance.md

As per https://forum.grin.mw/t/new-core-team-member-joltz/7186

Add joltz to core team

---

_layouts/default.html
assets/css/main.scss

As mentioned in the forum post, first banner on Grin website.

HF3 Banner

---

download.html

Forgot version update in title

---

download.html
index.html

v4.0.0 Update

---

_layouts/default.html

Post HF3 Banner

---

README.md

Add a step that has been missing to preview the website and the changes you make. helps those with minimal experience.

add final instruction to run site locally

---

assets/js/download.js

Fixes https://github.com/mimblewimble/site/issues/209.

Fix automatic OS selection

---

_posts/2020-07-22-grin-node-402-released.md
download.html
index.html

- New download links with new shamsum
- New blog post
For some reasons, the new post is not showing in the blog list. Any ideas @lehnberg ?

v4.0.2 release

---

fund.html

Not to be merged before https://github.com/mimblewimble/grin-pm/pull/333

Update funding amounts according to Q2 report

---

_includes/meta.html

These meta tags conform to the [standard](https://ogp.me/) for sharing data on social media sites. 
Feel free to leave feedback with preferred text - I used my best judgement.

add meta tags for social link display

---

governance.md

as per decision in governance meeting:
https://github.com/mimblewimble/grin-pm/blob/master/notes/20200908-meeting-governance.md#decision-remove-ignotus-as-bdfl
https://github.com/mimblewimble/grin-pm/blob/master/notes/20200908-meeting-governance.md#decision-remove-hashmap-from-core-team

remove @ignotus and @hashmap from core team

---

_includes/navigation.html
_layouts/default-black.html
_layouts/default.html

Replace GitHub link by "Documentation" link in top bar.

Add Documentation Link

---

_includes/navigation.html
download.html
fund.html
get-started.html
governance.md
index.html

Full list: https://validator.w3.org/nu/?doc=https%3A%2F%2Fgrin.mw%2F
Full list: https://validator.w3.org/nu/?doc=https%3A%2F%2Fgrin.mw%2Fget-started
Full list: https://validator.w3.org/nu/?doc=https%3A%2F%2Fgrin.mw%2Fdownload
Full list: https://validator.w3.org/nu/?doc=https%3A%2F%2Fgrin.mw%2Fgovernance
Full list: https://validator.w3.org/nu/?doc=https%3A%2F%2Fgrin.mw%2Fdownload

Fix W3C errors

---

download.html

Update grin-wallet to v5.0.3

---

open-research-problems.md

I removed the redundant section on kernel aggregation (which mostly duped the first section on BLS) and move the last section to its vacant place.
Also added links to CoinSwap proposal, add link to recent paper on ZK proofs and fixed some types.

Update Open Resource problems

---

download.html

URL: https://grin.mw/download
| Before  | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/8020386/111023581-dc969300-8414-11eb-9136-5c1bc2ef6372.png)  | ![image](https://user-images.githubusercontent.com/8020386/111023596-e61ffb00-8414-11eb-93e7-ceee84a0c4a1.png)  |

Add GRIN++ Android app

---

fund.html

Blocked by https://github.com/mimblewimble/grin-pm/pull/405/

Update fund status according to Q4 2020 report

---

_layouts/default.html

Update site banner to reflect latest hotfix version

Update banner to relfect 5.0.4 release

---

download.html

Update website for v5.0.4 release

---

_layouts/default.html
download.html

Remove emergency banner + Update grin to v5.1.0

---

download.html

Updated links and SHA256 checksums.

Updated grin download links to 5.1.2

---

assets/js/fund.js
fund.html

Fetch `final_balance` value from this API: `https://blockchain.info/balance?active=bc1q2x8gu8n85ylur5j83yflhpg5hf80nhnyem98k2pld46lf4czhmgsxq8wlu` to keep data up to date without manual editing.

Get actual fund balance from blockchain explorer

---

community.md

I added the Grinchat.mw SimpleX server to the community page now that it's been tested and is active.

updated community page

---

community.md

Keybase added back to community page

re-added Keybase chat

---

_sass/navigation.scss

I added a semi-transparent background to the navbar, it was requested by a few users on the forum.
https://forum.grin.mw/t/updates-to-grin-mw/11862/18
I also got rid of that random '*' in the first section, it did nothing for page alignment and lacked any other reason to exist that I could find.

Added background to navbar per community requests

---

CNAME
_sass/navigation.scss

Ignore the CNAME items, I was testing out using Github pages to preview the site and adding a custom domain, but it doesn't render the Jekyll formatted site.

Fixed navbar, no longer blends with background
