mimblewimble/site

_sass/_variables.scss, assets/css/main.scss, index.md
I kept being irritated at the low contrast on the two buttons "What's Mimblewimble" and the github button just below the smiley logo, and experimented. This version, reusing the color and bold border / outline makes these buttons fit-in better together with the Grin logo, and I made the :hover style pop out even more with fully black borders. Feels more clickable and readable this way. Good or bad? I think it's at least better than before :)
=> recolor whatis- and github-buttons

general_funding.md
Make the general funding page fairly static to
avoid obsolete information over time.
Let https://grin-tech.org/funding which is more
prominent in the website to capture current needs.
=> Fairly static Grin general funding page

_includes/navigation.html
I think the MP doc is important enough to not let it burried inside the wiki
Also "Chat" makes more sense that "Gitter" to most newcomers.
=> Rename Gitter to Chat, link to MP

_includes/footer.html
I have already seen the discord referenced as official in other channels (and a random opinion from the discord touted as official), and I think it is too wide an attack surface and liability to have it listed on the main site. it is a great community, but lots of trash talking, etc. would be too easy for it to be comandeered and used to pitch scams or alternative projects. the intentions of the speculators who founded and moderate the channel are not as pure as the core grin team, and the link on the main grin site does not reflect this fact.
I would love for my twitter @grinmw to be listed as official, but can't in clear conscience have it, as technically an unofficial channel, listed on the main site but deny the right of the discord. the twitter is narrow band and has a couple of core …
=> change twitter to grincouncil, remove discord link

assets/csv/entities.csv
```
Gary Yu @garyyu 12:21
@nijynot the https://grin-tech.org/friends becomes empty Hall of Fame after I merged mimblewimble/grin-pm#79
Could you please take a look the problem? thanks
nijynot @nijynot 21:17
@garyyu Found the problem. "Grin-pool.org" is not added in entities.csv, so it'll not render correctly.
If a new donation is added to the income_log.csv, then it's source must already exists as a to a row in entities.csv for it to work, if that makes sense.
We should probably move entities.csv over to grin-pm to make it easier to change/add.
Gary Yu @garyyu 21:19
thanks @nijynot
the situation is grin-pool.org’s donation don’t reach the threshold to be displayed in Friends of Grin (1,000 US$ for org).
if I add it into entities.csv, would you show it automatically into logos area? …
```
=> fix: Grin-pool.org is needed in entities, to match income_log.csv

_sass/friends.scss, friends.html
URLs in donation comments will turn into links.
Using the [linkifyjs](https://github.com/SoapBox/linkifyjs) library to do this.
Does not sanitze, so open to XSS attacks.
Should not be a problem as long as `script` tags are not merged into the `income_log.csv` comment column.
=> linkify urls in donation comments

assets/csv/entities.csv
this PR:
* fixes a comma typo slipped in as part of #120 that broke the CSV table; and
* points the grinmint logo to the asset uploaded as part of #120
=> fix: grinmint entry missing comma, correct logo url

_includes/banner.html, _layouts/default.html, assets/css/main.scss
As specified [here](https://www.grin-forum.org/t/grin-first-hard-fork-mid-july/5148).
Looks like this:
=> Add first HF warning banner

_includes/banner.html, assets/css/main.scss
=> Add download links for 2.0.0 in warning banner

fund.html, index.html
It seems like the release version is a unnecessary detail to keep in sync and updated so prominently on the main landing page.  Having the version incorrect (as it currently is) causes significant legitimacy issues for the new grin.mw website.  As a non-controversial temporary fix... this pull request fixes the version number.  As a long term solutions, I recommend removing this detail from the landing page.
The 'Grin Donation Address' led to a yeastplume.org page which is invalid. Suggest any replacement method be self hosted on grin.mw.
=> Update Landing Page / Remove Bad Donation Address

_includes/footer.html
as reported by b33rkeg:
> Hi, I see you are working on the website. I can't log in Github atm but the forum button in the footer redirects to https://grin-forum.org which is not working, but https://www.grin-forum.org works.
=> Fix broken forum link

fund.html, sec_audit.md, yeastplume.md
Fixes #151.
Blocked by https://github.com/mimblewimble/grin-pm/pull/209.
Also:
- Adds link to the security adit results on the audit page of the website, and sets its funding status to closed.
- Fixes a link to segwit adoption comparison table.
- Removes old Yeastplume donation addresses.
=> Do not display donation addresses directly on website

_layouts/default.html, assets/css/main.scss
Somehow a bit more sketchy to add a top banner warning. 
So instead it's a sticky red warning footer which does the job too.
Screenshot:
=> Add sticky warning footer for HF2

_includes/navigation.html, _layouts/default-black.html, _layouts/default.html, _sass/_markdown.scss, community.md
Following an [action point in the last dev meeting](https://github.com/mimblewimble/grin-pm/blob/master/notes/20191217-meeting-governance.md#5-switch-meeting-location-from-gitter-to-keybase), this PR adds a `Community` section to the website with:
* links to Keybase, forum, and mailing list
* information about how to join the main keybase team
* information about the bi-weekly meetings and links to meeting notes and agendas
=> Add community page with Keybase how-to

download.html
fixes #173 
The download URL for `grin-wallet v2.1.0` for linux links to `grin v2.1.1`. This PR corrects it. Checksums have been verified to be correct.
=> fix: linux grin-wallet download url

_includes/navigation.html, _layouts/default-black.html, _layouts/default.html, _sass/governance.scss, assets/css/main.scss, governance.md
This PR introduces a governance section on the website, which provides:
* info on Grin's RFC and governance processes
* info about to the core, node, and wallet teams
https://lehnberg.net/site/governance
=> add Governance section

community.md
Noticed forum link doesn't work without www. may need to fix on webserver side.
=> grin-forum domain doesn't server without www

_includes/navigation.html, _layouts/default-black.html, _layouts/default.html, _sass/fund.scss, fund.html, index.html
In accordance with #172, this PR reworks the "General Fund" page into a new `Funding` section.
* Links to financials
* Updates general fund amount and links to a source
* Brings in the community funding principles from `funding.md`
* Removes Friends of Grin from the nav links
* Links to Friends of Grin from the funding page and also from index.
https://lehnberg.net/site/fund
=> Introduce Funding section

_includes/footer.html, _layouts/default.html, assets/csv/entities.csv, community.md, open-research-problems.md, page-contribution-howto.md, sec_audit.md, yeastplume.md
This PR:
1. Fixes a broken link to keybase as reported by @johndavies24
1. Replaces old grin-forum.org links with the new https://forum.grin.mw URL
1. Replaces links to gitter with the URL to the keybase team
=> Fix: Various URL corrections

download.html
SHA256 hash outputs are in upper case on Windows machines. This PR changes the formatting of hashes for Windows releases to reflect what the user will see when verifying locally.
=> Fix hash formatting for Windows users

_includes/navigation.html, _layouts/default-black.html, _layouts/default.html, _layouts/post.html, _posts/2020-07-02-grin-4-released.md, blog/index.md
This PR adds a new blog section on the website, `grin.mw/blog`, for important core team announcements, such as:
* new releases
* security vulnerabilities
* governance decisions
Previously, this has been handled in forum posts, and while the practice of creating forum posts where community members can discuss announcements should continue, it also makes sense to keep all announcements in one place visible to the public, and clearly version tracked.
* Improve menu navigation with relative links that do not break if accessed from within the `/blog` hierarchy
* Add "Blog" menu navigation item, that links to a default "Blog page" with a simple list of blog posts
* Add example blog post, a verbatim copy of Yeastplume's recent 4.0.0 announcement on the forum.
* https://lehnberg.net/site/blog/
* …
=> Create Blog section for announcements

_posts/2020-07-13-grin-node-401-released.md, download.html, index.html
* Bumps version number on the website
* Adds blog post announcement
* Adds SHA256 hashes and download links:
```bash
$ shasum -a 256 grin-v4.0.1-linux-amd64.tar.gz
shasum -a 256 grin-v4.0.1-macos.tar.gz
shasum -a 256 grin-v4.0.1-win-x64.zip
1bbc0ae41b3fbf21aad1a58b655385f9ebacc7ef99f83a4f6d078f149e7d67f5  grin-v4.0.1-linux-amd64.tar.gz
185b0a9cd32ff119d1e14c2efffa3cf7a9dac8b48fbe864e2f40fa7b93834ce3  grin-v4.0.1-macos.tar.gz
3ee60a2180e4fbcc638166cdcc2415f9ba17f2be0e6312ace8148fa722fafef7  grin-v4.0.1-win-x64.zip
```
=> Announce Grin v4.0.1 release

_sass/index.scss
The image of "section 1" cover the headline of "section 2" on mobile. (#201 )
=> FIX issue #201: The image cover the headline on mobile

_includes/footer.html
twitter.com/grinmw is suspended and the owner can't be reached.
Remove it for now.
=> remove twitter from footer

_sass/get-started.scss, _sass/navigation.scss, assets/css/main.scss
Design issues on 'Get Started' page - fix #213
1. The steps numbers cover the nav menu on mobile.
2. The steps numbers cover the 'IMPORTANT UPDATE' on mobile.
3. The steps buttons cover the 'IMPORTANT UPDATE' on desktop.
URL: https://grin.mw/get-started
=> FIX Design issues on 'Get Started' page

_sass/download.scss
**Some minor changes:**
- Changed page headline padding (same 'Get Started' page).
- Remove 'Download' headline border bottom.
- Change tabs padding.
- Add border top to the 'Community Projects' section.
- Change 'Community Projects' headline padding.
- Add border radius to 'Ironbelly' (like the official logo)
=> Design improvement for 'Download' page

_includes/footer.html, community.md, policies/code_of_conduct.md
As per https://github.com/mimblewimble/grin-pm/issues/309
1. Updates the code of conduct (CoC) to follow [contributor covenant v2.0](https://www.contributor-covenant.org/version/2/0/code_of_conduct.html) with no significant changes in wording. (Previously the CoC was based on the one used by Rust Language, which in turn is based off contributor covenant v1.3.)
2. Adds the CoC to the website at `https://grin.mw/policies/code_of_conduct`.
3. Adds a link to the CoC in the footer, and groups it together with the link to `/grin-security`
4. Adds a reference to the CoC and call to actions at the bottom of `https://grin.mw/community`
* Each repo in the `/mimblewimble` Github org will have its `CODE_OF_CONDUCT.md` updated to point to `https://grin.mw/policies/code_of_conduct`.
* Keybase stickies …
=> Add an updated Code of Conduct

download.html
Fix quickstart docs link, missing 'https://' https://github.com/mimblewimble/site/pull/233/commits/c7e5578ea40dd97f189e43e47eae62a42e6f332d
=> Fix 'quickstart' docs link

blog/index.md
Replaces a broken link to the now removed core team and simplifies blog description
=> Fix blog description

_layouts/default.html, assets/css/main.scss
Adds a banner with a notice about hashrate concerns + encouragement to wait for more confirmations before accepting payments.
- Hashrate has increased significantly on the Grin network recently
- Nicehash appears to have a pool with a larger hashrate than Grin network
- Price on Nicehash has doubled recently
- Significantly more than 50% of current Grin network hashrate is unknown
All of these factors should lead to caution when accepting large payments with low confirmations until the network hashrate dynamics stabilize.
=> Add hashrate notice banner

_layouts/default.html
Adds a banner for emergency update. 
TODO: once blog post is completed, link to that instead
=> Add 5.0.3 upgrade notice banner

download.html
Ironbelly wallet is discontinued, this change removes its mention from the download page. 
Context: https://forum.grin.mw/t/ironbelly-is-spitting-fire-no-longer/11003
=> Remove Ironbelly wallet

_includes/footer.html, index.html
- Main page still links to merch site (https://tmgox.com/) which does not exist.  Removed link and reference to it.
- Footer (which shows on main page) links to 'news' substack (https://grinnews.substack.com/) which had not been updated since 2022.  I updated link to the actively maintained substack (https://grinpost.substack.com/).  If that new link is not appropriate for the main page, let me know and I can re-submit with the 'news' link removed.  I do not recommend leaving the old substack as it make the project look dormant. 
(I will try to make any future pull requests one issue related so they are easy to review/merge-or-reject).
=> Remove broken link and update outdated link on main page

Gemfile.lock, _includes/navigation.html, download.html
This pull request makes an edit of 'structure' to the website.  Specifically, it removes 'blog' from top menu of the [grin.mw](http://grin.mw/) website. 
**Rational:** The 'blog' tab is prominent and the last post was in Jan 2021.  A visitor could not be blamed for thinking grin was "dead" given that condition. 
**Options:**
1. Start making blog posts (not recommended since it takes a lot of volunteer time from a senior member and would eventually become stale again)
2. Remove 'blog' and replace with 'forum'.  The forum is part of the [grin.mw](http://grin.mw/) domain so it fits.  Additionally, it is 'self maintaining' in that activity happens naturally so visitors would see that things are happening.  (_recommended_).
3. Remove 'blog' and replace it with nothing (acceptable option, but I …
=> Update stale blog link to active forum link.

_layouts/default-black.html, _layouts/default.html, assets/js/download.js, download.html, index.html, site.webmanifest
**Download links:**
This pull request provides a download.js file update that will get the grin-wallet and grin versions from the github latest release API and update the links on the download.html.  The download links will now always be up to date.  If the API fails for any reason, the links default to the github latest release page.  That is less good because they have to find the file they need, but it is still better because it won't cause confusion as to what the latest link is.
**Hashfiles**
I initially tried to make it so that the js also extracted the hash from the github txt hashfile file and displayed the hash on the page where the hash used to be provided.  However, it turns out that browsers will not let you open (read from) a txt file pulled from a different domain then the …
=> Download Links Pull From GitHub API

fund.html
* Removes legacy donation options
* Keeps only the Bitcoin SegWit donation option
* Updates the transparency report link from 2023 Q1 to 2024 Q4 (which will be merged soon)
=> Update donation address links

community.md
The link to the SimpleX chat server was pointing to the forum and I have fixed that
=> Fixed SimpleX chat server link
